apiVersion: v2
name: java-spring-boot-api
description: A Helm chart for Java Spring Boot API
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: helm-template-001
    version: 0.1.3
    repository: https://code360Pro.github.io/helm-template-001/

