helm-template-001:
  environment: dev
  namespace: rp-dev

  application:
    port: 8080

  serviceAccount:
    # The name of the service account to use.
    name: "" # Leave empty to generate automatically, or set to override
  replicaCount: 1
